"""Add PendingConfirmation table

Revision ID: 14a39ff86256
Revises: ace1a1df32ab
Create Date: 2026-06-27 20:05:58.051898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14a39ff86256'
down_revision: Union[str, Sequence[str], None] = 'ace1a1df32ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_confirmations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('whatsapp_phone', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('resource_title', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_confirmations_whatsapp_phone'), 'pending_confirmations', ['whatsapp_phone'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pending_confirmations_whatsapp_phone'), table_name='pending_confirmations')
    op.drop_table('pending_confirmations')
    # ### end Alembic commands ###
